Repository bafraikin/hypertube_node, pull requests merged in 2020-02, with the labels that each got.

#13 [Feature] adding user.isEmpty again
  back/src/app/controllers/user.ts
  back/src/app/models/user.ts
Labels: enhancement

#17 [Fix] emoji in route and fix of auth
  back/package-lock.json
  back/package.json
  back/src/app/controllers/authenticate.ts
  back/src/app/controllers/user.ts
  back/src/app/models/user.ts
  back/src/settings/app.ts
  back/src/settings/connect_pg.ts
  back/src/settings/logger.ts
  back/src/settings/passport.ts
  back/src/settings/route.ts
  back/src/settings/server.ts
  back/test
  back/tsconfig.json
  front/src/components/HelloWorld.vue
  front/src/components/layouts/form_signin.vue
  front/src/components/layouts/form_signup.vue
  front/src/components/layouts/modal_signin.vue
  front/src/components/layouts/modal_signup.vue
  front/src/components/layouts/navbar.vue
  front/src/config/axios_default.js
  front/src/store/index.ts
  front/src/views/Film-info.vue
  front/src/views/Film-list.vue
Labels: Bugfix

#18 Switch film list to vuetify
  back/src/app/controllers/movies.ts
  back/src/app/models/movies.ts
  back/src/settings/route.ts
  back/tsconfig.json
  front/src/App.vue
  front/src/components/HelloWorld.vue
  front/src/components/MovieDetails.vue
  front/src/components/MovieResearch.vue
  front/src/router/index.ts
  front/src/views/About.vue
  front/src/views/Film-download.vue
  front/src/views/Film-info.vue
  front/src/views/Film-list.vue
  front/src/views/Film-play.vue
  front/src/views/Home.vue
Labels: enhancement

#19 Make vue persistent between refresh in brief save the f world
  back/src/app/controllers/authenticate.ts
  front/Dockerfile
  front/package.json
  front/src/components/layouts/form_signin.vue
  front/src/components/layouts/navbar.vue
  front/src/config/axios_default.js
  front/src/store/index.ts
  front/yarn.lock
Labels: enhancement

#20 added alert in the application, and corrected few status on request
  back/src/app/controllers/user.ts
  front/package.json
  front/src/components/layouts/alerts.vue
  front/src/components/layouts/layout.vue
  front/src/config/axios_default.js
  front/src/main.ts
  front/yarn.lock
Labels: enhancement

#23 Display user profile
  back/src/app/controllers/comments.ts
  back/src/app/controllers/index.ts
  back/src/app/controllers/movies.ts
  back/src/app/controllers/user.ts
  back/src/app/models/comment.ts
  back/src/app/models/movies.ts
  back/src/app/models/user.ts
  back/src/settings/connect_pg.ts
  back/src/settings/route.ts
  front/src/components/Comments.vue
  front/src/components/MovieDetails.vue
  front/src/router/index.ts
  front/src/views/Film-play.vue
  front/src/views/Profile.vue
  front/yarn.lock
Labels: enhancement

#27 Update Readme to better match new requirement
  README.md
Labels: enhancement

#25 Oauth forty two
  .gitignore
  back/.env
  back/.gitignore
  back/package-lock.json
  back/package.json
  back/src/app/controllers/authenticate.ts
  back/src/app/models/user.ts
  back/src/settings/passport.ts
  back/src/settings/route.ts
  front/src/components/layouts/form_signin.vue
  front/src/components/layouts/form_signup.vue
  front/src/components/layouts/oauth.vue
  front/src/config/axios_default.js
  front/src/router/index.ts
  front/src/views/oauth42.vue
Labels: enhancement

#53 handling error and fix bad magnet link
  back/src/app/controllers/comments.ts
  back/src/app/controllers/movies.ts
  back/src/app/controllers/player.ts
  back/src/app/controllers/torrent.ts
  back/src/app/controllers/user.ts
  back/src/app/controllers/watch.ts
  back/src/app/services/torrent.ts
  front/src/components/TorrentList.vue
Labels: Bugfix, enhancement

#57 Les route en front: / . /movie . /user . /player
  front/src/components/MovieDetails.vue
  front/src/components/NewHome.vue
  front/src/router/index.ts
Labels: enhancement

#59 add no torrent found
  back/src/app/controllers/torrent.ts
  back/src/app/services/torrent.ts
  front/src/components/TorrentList.vue
Labels: Bugfix

#52 Subtitles
  back/.gitignore
  back/package-lock.json
  back/package.json
  back/src/app/controllers/index.ts
  back/src/app/controllers/subtitles.ts
  back/src/app/services/subtitles.ts
  back/src/settings/route.ts
  back/src/settings/server.ts
  back/sub/file
  front/src/components/TorrentList.vue
  front/src/views/Film-play.vue
Labels: enhancement

#63 fixed
  front/src/components/layouts/alerts.vue
  front/src/views/oauth42.vue
  front/src/views/oauthGoogle.vue
Labels: enhancement

#62 fixed
  front/src/components/NewHome.vue
Labels: Bugfix

#61 Mail and forgot password
  README.md
  back/src/app/controllers/mailer.ts
  back/src/app/controllers/user.ts
  back/src/app/models/user.ts
  back/src/settings/route.ts
  front/src/components/layouts/alerts.vue
  front/src/components/layouts/form_signin.vue
  front/src/components/layouts/modal_signin.vue
  front/src/router/index.ts
  front/src/views/resetpassword.vue
Labels: enhancement

#64 Profile management
  back/src/app/controllers/user.ts
  back/src/app/models/user.ts
  back/src/settings/route.ts
  back/src/settings/server.ts
  front/src/components/layouts/modal_profil.vue
  front/src/components/layouts/navbar.vue
  front/src/components/layouts/profil_modif.vue
Labels: enhancement

#66 little improvement off the UX of the research bar
  front/src/components/ResearchBar.vue
Labels: enhancement

#67 Profile pic
  .gitignore
  back/.gitignore
  back/package-lock.json
  back/package.json
  back/src/app/controllers/user.ts
  back/src/app/models/comment.ts
  back/src/app/models/user.ts
  back/src/app/services/picUpload.ts
  back/src/settings/route.ts
  back/src/settings/server.ts
  front/public/user_default.png
  front/src/components/layouts/form_signup.vue
  front/src/components/layouts/profil_modif.vue
  front/src/views/Profile.vue
Labels: enhancement

#73 removing most of the useless consol.log and changing the rest
  back/src/app/controllers/player.ts
  back/src/app/controllers/subtitles.ts
  back/src/app/services/OMDB.ts
  back/src/app/services/subtitles.ts
  back/src/settings/app.ts
Labels: Bugfix

#74 Multilingual
  back/src/app/controllers/movies.ts
  back/src/app/controllers/user.ts
  back/src/app/models/user.ts
  back/src/app/services/OMDB.ts
  back/src/settings/route.ts
  front/package.json
  front/src/components/Casting.vue
  front/src/components/Comments.vue
  front/src/components/MovieDetails.vue
  front/src/components/MovieVignette.vue
  front/src/components/NewHome.vue
  front/src/components/ResearchBar.vue
  front/src/components/TorrentList.vue
  front/src/components/layouts/LangButton.vue
  front/src/components/layouts/alerts.vue
  front/src/components/layouts/form_signin.vue
  front/src/components/layouts/form_signup.vue
  front/src/components/layouts/modal_profil.vue
  front/src/components/layouts/modal_signin.vue
  front/src/components/layouts/modal_signup.vue
  front/src/components/layouts/navbar.vue
  front/src/components/layouts/profil_modif.vue
  front/src/lang/index.ts
  front/src/lang/translations/en.json
  front/src/lang/translations/fr.json
  front/src/main.ts
  front/src/store/index.ts
  front/src/views/Film-play.vue
  front/src/views/Profile.vue
  front/src/views/oauth42.vue
  front/src/views/oauthGoogle.vue
  front/tsconfig.json
  front/yarn.lock
Labels: enhancement
